CoachPosition.Web/Controllers/StationController.cs
using CoachPosition.Data.Abstract;
using CoachPosition.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoachPosition.Web.Controllers
{
    [Authorize]
    public class StationController : Controller
    {
        private IRepository _repository;

        public StationController(IRepository repository)
        {
            _repository = repository;
        }

        public ActionResult AddWay()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddWay(Train train)
        {
            if (ModelState.IsValid)
            {
                int numWay = train.NumWay;
                train = _repository.Trains.FirstOrDefault(f => f.NumTrain == train.NumTrain);
                if (train != null)
                {
                    train.NumWay = numWay;
                    _repository.SaveTrain(train);
                }
                else
                {
                    ViewBag.Message = "Данного поезда не существует, пожалуйста, проверьте введенные данные. ";
                    return View();
                }
                ViewBag.Message = "Путь - " + train.NumWay + ", для поезда - " + train.NumTrain + ", успешно сохранен.";
            }
            else
            {
                ViewBag.Message = "Что-то пошло не так, пожалуйста, проверьте формат, введенных данных и повторите попытку.";
            }
            return View();
        }
	}
}

CoachPosition.Web/Views/Station/AddWay.cshtml
@model CoachPosition.Data.Entities.Train
@{
    ViewBag.Title = "AddTrain";
}

<h3 class="info_name">Информация о номере пути для прибывающего поезда *</h3>
@using (Html.BeginForm("AddWay", "Station", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <h3 class="message">@ViewBag.Message</h3>
    <div class="div_fields">
        <div class="editor_label">
            @Html.LabelFor(m => m.NumTrain)
        </div>
        <div>
            @Html.TextBoxFor(m => m.NumTrain, new { @class = "manager_field" })
            @Html.ValidationMessageFor(m => m.NumTrain, null, new { @class = "red_color" })
            @Html.HiddenFor(m => m.NumCars, new { Value = "0" })
        </div>
        <div class="editor_label">
            @Html.LabelFor(m => m.NumWay)
        </div>
        <div>
            @Html.TextBoxFor(m => m.NumWay, new { @class = "manager_field" })
            @Html.ValidationMessageFor(m => m.NumWay, null, new { @class = "red_color" })
        </div>
    </div>
    <div class="btn_center">
        @if (ViewBag.Message == null)
        {
            <input type="submit" class="btn_main" value="Сохранить" />
        }
        else
        {
            <input type="submit" class="btn_main" value="Редактировать" />
        }
    </div>
}
<h4 id="warn_info">* Для ввода номера пути используются цифры.</h4>